In [1]:
import sqlalchemy as db
from functions import DataBaseV2
from sqlalchemy import create_engine
import pandas as pd
import sys
sys.path.insert(0, "..")
from stratégie_nettoyage_donnees import nettoyage_df

In [2]:
# Création d'une base de données
database = DataBaseV2(db_name='db', db_type='sqlite')

In [12]:
engine = create_engine('sqlite:///db.db', echo=False)

In [10]:
df = pd.read_csv("..\data\survey.csv")
df = nettoyage_df(df)
df

d:\Documents\Ecole\Rendus_Ecole_Simplon\PCO\E1\nouveau_projet_perso\code\Base-de-Donnee\..\stratégie_nettoyage_donnees.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["self_employed"].fillna("Other", inplace=True)
d:\Documents\Ecole\Rendus_Ecole_Simplon\PCO\E1\nouveau_projet_perso\code\Base-de-Donnee\..\stratégie_nettoyage_donnees.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["work_interfere"].fillna("Not concerned", inplace=True)

,Age,Gender,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,benefits,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,37,Female,Other,No,Yes,Often,6-25,No,Yes,Yes,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
1,44,Male,Other,No,No,Rarely,More than 1000,No,No,Don't know,...,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No
2,32,Male,Other,No,No,Rarely,6-25,No,Yes,No,...,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No
3,31,Male,Other,Yes,Yes,Often,26-100,No,Yes,No,...,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes
4,31,Male,Other,No,No,Never,100-500,Yes,Yes,Yes,...,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,26,Male,No,No,Yes,Not concerned,26-100,No,Yes,No,...,Don't know,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No
1255,32,Male,No,Yes,Yes,Often,26-100,Yes,Yes,Yes,...,Yes,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No
1256,34,Male,No,Yes,Yes,Sometimes,More than 1000,No,Yes,Yes,...,Don't know,Somewhat difficult,Yes,Yes,No,No,No,No,No,No
1257,46,Female,No,No,No,Not concerned,100-500,Yes,Yes,No,...,Don't know,Don't know,Yes,No,No,No,No,No,No,No
1258,25,Male,No,Yes,Yes,Sometimes,26-100,No,No,Yes,...,Yes,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No

In [11]:
database.delete_table('questionnaires')
df.to_sql('questionnaires', con=engine, if_exists='fail')

Table questionnaires deleted successfully

1254